//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ansatte : CommonClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ansatte()
        {
            this.Tuneringer = new HashSet<Tuneringer>();
        }
    
        public int Id { get; set; }
        public int Løn { get; set; }
        public string Jobtype { get; set; }
        public string Dommer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuneringer> Tuneringer { get; set; }
    }
}
