//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spillere : CommonClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spillere()
        {
            this.Sponsorer = new HashSet<Sponsorer>();
            this.Tuneringer = new HashSet<Tuneringer>();
        }
    
        public int SpillerId { get; set; }
        public string SummonerNavn { get; set; }
        public int Rang { get; set; }
        public string Tuneringstype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sponsorer> Sponsorer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuneringer> Tuneringer { get; set; }
    }
}
